global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'iot_devices'
    static_configs:
      - targets:
          - '192.168.1.254:80'
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics

rule_files:
  - /etc/prometheus/alert_rules.yml
